# Generated by Django 3.2.6 on 2021-08-30 21:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snackes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snack',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='snack',
            name='reviewer',
        ),
        migrations.AddField(
            model_name='snack',
            name='description',
            field=models.TextField(default=datetime.datetime(2021, 8, 30, 21, 27, 53, 65899, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snack',
            name='purchaser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='snack',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
